### PR TITLE
Add cursor pagination

### PR DESCRIPTION
**Pull request by AyoobMH**
* **Please check if the PR fulfills these requirements**
- [X] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?**
Feature

* **What is the current behavior?**
There is no cursorPaginate support currently.

* **What is the new behavior (if this is a feature change)?**
Adding the cursorPaginate method to the package. I have added a boolean to enable/disable the cursor_paginator method, and a cursor query parameter.

* **Does this PR introduce a breaking change?**
No

* **Other information**:

### CODE REVIEW

**Comment by freekmurze** [comment]
Could you resolve the conflicts?

**Comment by AyoobMH** [comment]
@freekmurze conflicts resolved!

**Comment by freekmurze** [comment]
Looks good!

Could you add a section about what cursor pagination is and how you can use it in the readme?

**Comment by AyoobMH** [comment]
> Looks good!
> 
> 
> 
> Could you add a section about what cursor pagination is and how you can use it in the readme?

Sure, I'll modify the readme!

**Comment by AyoobMH** [comment]
@freekmurze readme has been modified!

**Comment by freekmurze** [comment]
Thanks!

**Pull request merged**
